name: GLaDOS-checkin

on:
  push:
  pull_request:
  watch:
    types: [ started ]
  schedule:
    - cron: 16/5 * * * *

jobs:
  GLaDOS-checkin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: checkin
        env:
          COOKIE: ${{ secrets.COOKIE }}
        run: |
          ./checkin.sh
